// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nlaxxynsulaytdstazmz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5sYXh4eW5zdWxheXRkc3Rhem16Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0MzMwMDAsImV4cCI6MjA2ODAwOTAwMH0.y4sWYnzMnuNZxbVFsAyD1fLzsrJKu3SAa3rxlwuRrfU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});